#!/bin/sh

# base packages
sudo xbps-install -Su base-devel libX11-devel libXft-devel libXinerama-devel harfbuzz-devel libXext-devel libXrender-devel libxcb-devel libXScrnSaver-devel freetype-devel fontconfig-devel gd-devel xorg-server libXrandr-devel xinit xrdb xrandr xauth xf86-video-intel xf86-input-libinput unclutter xclip xsel dbus elogind autoconf autoconf-archive pkg-config libbsd xkb-switch xdg-user-dirs gtk2-engines
sudo ln -s /etc/sv/dbus /var/service
sudo ln -s /etc/sv/elogind /var/service

# audio/music stuff
sudo xbps-install -S pipewire alsa-pipewire bluez libspa-bluetooth libpulseaudio sof-firmware pamixer mpc mpd playerctl ncmpcpp 

# screen utils 
sudo xbps-install -S brightnessctl redshift scrot ueberzug autorandr dunst feh

# network
sudo xbps-install -S NetworkManager openresolv wireguard-dkms wireguard-tools

# archivers
sudo xbps-install -S zip unzip unrar p7zip atool 

# useful utils 
sudo xbps-install -S curl wget bc ripgrep translate-shell keyd clipnotify clipmenu envycontrol fzf fd bat acpi

# programming languages/build systems
sudo xbps-install -S rust go cmake ninja nodejs 
# languages formatters/linters 
sudo xbps-install -S shellcheck StyLua 

# Necessary software 
sudo xbps-install -S calibre telegram-desktop firefox chromium 

# minimal (suckless) software 
sudo xbps-install -S poppler zathura zathura-pdf-mupdf lf sxiv lazygit pass btop 

# zsh setup 
sudo xbps-install -S zsh zsh-completions
curl -sS https://starship.rs/install.sh | sh

sudo rm -rf /var/service/dhcpcd
sudo rm -rf /var/service/wpa_supplicant
sudo ln -s /etc/sv/NetworkManager /var/service
sudo ln -s /etc/sv/wireguard /var/service
 

 
